### ISSUE TITLE
include source type in evidence item suggested change diffs

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#1020]
Currently we only show a diff on the source title, source type should also be included in the diffs with its own before -> diff -> final block.

**Comment by susannasiebert** [comment]
The diff in this situation works on the source object itself. source_type is an attribute of the source object. As thus it won’t show as a separate item since what you are really changing is the source object. Right now we’re displaying the citation as a representation of the source object. We can change what gets included when we display the diff for a source object. We could include the source_type attribute but it would then always be displayed, even if the new source is of the same source type
