### ISSUE TITLE
Add ability to search for evidence with clinical trial NCT ID

### ISSUE THREAD

**Issue by malachig** [griffithlab/civic-client#1054]
Under advanced search for evidence it would great if we could do the following searches:

- All evidence with any Clinical Trial ID associated with their source (is defined)
- Evidence associated with a specific Clinical Trial ID

**Comment by arpaddanos** [comment]
One thought is that a clinical trial publication might also yield some evidence items that we might not always want to associate directly with the trial. Like perhaps some preclinical figures in a report associated with a trial might yield a few lower level EIDs for us that don't necessarily need to be labeled as associated with a clinical trial. Also if the trial provides case study level data from the population - what mutation they had, what disease, what the individual outcome was - then we create case study level EIDs. But in this case it might also be nice to have these case studies associated with the trial they came from. Another situation is a paper which is a meta study that uses data from multiple trials as well. Perhaps one might extract multiple EIDs from this publication, one for each clinical trial, and one might want those EIDs labeled with only the trial that the data in the EID is derived from, yet presumably that publication would be associated with all of the clinical trials. These are some of the reasons I would suggest considering having clinical trial data manually entered on an EID level instead of the publication level.
