### ISSUE TITLE
Page does not refresh automatically when signing out

### ISSUE THREAD

**Issue by zlskidmore** [griffithlab/civic-client#265]
When signing out the page does not refresh automatically making it seem like no sign out has occurred.

**Comment by jmcmichael** [comment]
I believe the state refresh that now occurs after signout will force all UI elements to their logged-out state, and this appeared to work on all of the pages I tried - please let me know if you see any UI elements remaining in their logged-in state.

**Comment by rlesurf** [comment]
The log out doesn't seem to work for me - it logs out, but doesn't 'show' that it's logged out unless I manually refresh the page. Using Mac Chrome

**Comment by malachig** [comment]
This still happens.  If I sign out, I must refresh the page.  Otherwise it is not obvious that I have signed out.  If I do not manually refresh, I can continue to browse around and it is looks like I am signed in, including showing the Add and Suggest buttons.  I can even submit evidence still.  It appears that the only way to actually log out is to press the sign out button and then manually reload.

**Comment by CodyRamirez** [comment]
This problem is made more confusing because when I go to sign out, the "sign out" button is not "highlighted" in some way. For example, when I hover over "Source Suggestions" or "My Account" my mouse pointer  changes into a finger. This visual cue does not happen for me when using Chrome instead it turns into a I-beam pointer.

**Comment by jmcmichael** [comment]
User is now returned to homepage upon signout.
