### ISSUE TITLE
Source curation queue - not updating?

### ISSUE THREAD

**Issue by marvolauk** [griffithlab/civic-client#603]
Hello,

I don't have permissions to modify or reject papers that are part of the source curation queue. There is a paper that looks like variants have already been included into civic (specifically the FGFR2-TACC3 and ERRFI1 events from Borad et al). It isn't clear to me how one would go about flagging that information from papers in the curation have already been entered into CiVIC? Is this something that would be highlighted on the variant talk page for example?

Cheers,

Martin

**Comment by malachig** [comment]
Yeah, so you can see the list of evidence records associated with each source in the curation queue.  As for deciding when the paper has been exhausted of evidence we are hoping that this will be discussed as comments on the source page itself.  We are going to add a talk page for the source so that discussion about the merits of the paper itself can go where they make most sense (on the source page for that paper).

This issue is here and is considered high priority: 
https://github.com/genome/civic-client/issues/548

**Comment by susannasiebert** [comment]
This has been addressed. Resolving.
