### ISSUE TITLE
Need to add "could not find disease" box to the edit evidence form

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#729]
Currently, new diseases can only be added through the add evidence page. The help text indicates this should be an option in the edit evidence page as well.
<img width="1093" alt="screen shot 2017-04-11 at 3 43 42 pm" src="https://cloud.githubusercontent.com/assets/8527125/24930183/37c2f4e0-1ece-11e7-826e-2eeb706b5486.png">

**Comment by juheon** [comment]
There are three edit evidence pages
* EDIT EVIDENCE
* ADD EVIDENCE
* SUGGEST SOURCE

  Unlike other pages, "Disease" is not required input in SUGGEST SOURCE page. On the top of the SUGGEST SOURCE page, it says "only the Pubmed ID and Comment are required". I guess the client recognizes a blank field for Disease as "Could not find a disease", and this is the reason why there is no checkbox. 
  I agree with KK's comment. To avoid confusion, it would be better to have the same UI and to add the checkbox in SUGGEST SOURCE page.

**Comment by jmcmichael** [comment]
Source Suggestions don't have quite the same level of importance as Genes, Variants, Evidence - they're meant to get a bare-minimum of input required to justify inclusion of a source into CIViC's database. So I think we can ignore the disease checkbox there - users are instructed they can leave it blank.

We should probably normalize the disease fields in the Edit and Add Evidence forms, since those two forms essentially refer to the same entity. 

Try porting these three angular-formly field definition objects from the Add Evidence form:

https://github.com/genome/civic-client/blob/master/src/app/views/add/evidence/addEvidenceBasic.js#L339-L402

to replace the single 'disease' field definition object in the Edit Evidence form here:

https://github.com/genome/civic-client/blob/master/src/app/views/add/evidence/addEvidenceBasic.js#L339-L402

One note - several of the Add Evidence form field definition objects contain controller logic that looks in the stateParams for values with which it then uses to populate its field. The edit form doesn't require these controllers. For example, you can drop this controller from the Add form when you're moving it to the Edit form:

https://github.com/genome/civic-client/blob/master/src/app/views/add/evidence/addEvidenceBasic.js#L369-L377

**Comment by juheon** [comment]
Based on the following result, I think both the edit form and add form do not require the controller. Are there any other cases that I missed for the add form? 

I looked into the Disease fields in ADD EVIDENCE and EDIT EVIDENCE, and I found the entry points for each pages are

ADD EVIDENCE
* HOME page > ADD button on the top right
* VARIANT page > ADD button on the top right

EDIT EVIDENCE
* VARIANT page > EDIT button on the top right

For these cases, the controller is called but $stateParams.disease is always undefined.

**Comment by jmcmichael** [comment]
Yes, there's an 'Add Evidence Item' button on each row of the source suggestion grid that populates the form with the suggestion's attributes, including disease:

https://civic.genome.wustl.edu/curation/sources

**Comment by juheon** [comment]
#795

**Comment by obigriffith** [comment]
Just pinging this thread. Looks like this is still an issue.
