### ISSUE TITLE
Add an Blank Entry Option for Chromosome Number.

### ISSUE THREAD

**Issue by KujanL** [griffithlab/civic-client#771]
I had accidentally selected the chromosome of one of the variants I was working on and I realized after that it had been submitted in a previous revision. Before I submitted my revision, I went back and tried to delete my chromosome selection, but there was no option to do so (to make the entry blank). Therefore, I had to start my revision all over again. 
![screen shot 2017-06-05 at 9 44 51 am](https://cloud.githubusercontent.com/assets/15361912/26786173/ac44956e-49d3-11e7-92e4-5d67e802418e.png)

**Comment by juheon** [comment]
I edited the original script to solve this issue and tried to upload it to master branch but it said.

remote: Permission to genome/civic-client.git denied to juheon.
fatal: unable to access 'https://github.com/genome/civic-client.git/': The requested URL returned error: 403

Is there a specific branch that I can upload?

**Comment by malachig** [comment]
Hi @juheon, in general you should always create a new branch for each issue you tackle, make the changes on that branch, test them in a dev instance of the site, then make a Pull Request to ask that it be merged into the master branch.  I have sent you a detailed overview of this in Slack.  You can also get a walk through of how to do this from various folks in the lab such as @jmcmichael, @ahwagner, @acoffman, @yanyangfeng, and others.

Once you have a pull request you can refer to it from this issue so that a link between the issue and the fix is created.

**Comment by malachig** [comment]
Thanks @juheon
