### ISSUE TITLE
Add Disease implicated attribute to Variant advanced search

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#837]
Users wanting to generate a list of variants for a capture panel need to be able to specify a disease. Search will use evidence item's disease field to satisfy searches using this criteria.

Query builder will look something like:

Disease [ user text input ] [is,is not] implicated

**Comment by susannasiebert** [comment]
This can gets a bit complicated on the backend depending on how exactly we want to the "is not implicated" query to behave. Given a variant V that has two evidence items, one with disease D1, the other with disease D2. The default behavior for "is not implicated with disease D1" would still return variant V because it is linked to a disease that is not D1. However, I don't think that this is the behavior we want here.
