### ISSUE TITLE
Add Evidence from Source Suggestions queue is changing the disease

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#847]
![screen shot 2018-01-29 at 3 42 36 pm](https://user-images.githubusercontent.com/8527125/35536034-3a472d70-050b-11e8-8de8-84a338e8e298.png)
See bottom entry (Cholangiocarcinoma)
![screen shot 2018-01-29 at 3 42 46 pm](https://user-images.githubusercontent.com/8527125/35536035-3a5b1d1c-050b-11e8-8640-80358d57419c.png)
See disease entry

**Comment by jmcmichael** [comment]
This looks like a server issue (or perhaps the client should be fetching drug information in a different way). Currently, the Add Evidence disease field uses the /diseases endpoint to query the name of the drug like this:

http://127.0.0.1:3001/api/diseases?query=Cholangiocarcinoma

It returns an array of drugs that match the query, and the disease field is populated with the first item from that array - assuming that since the drug name should be an exact match, it'll be the first in the results. For most queries, this seems to work (I tried several other suggested source rows, and the drugs were properly displayed. For some reason the query for 'Cholangiocarcinoma' returns an array of drug objects w/ Cholangiocarcinoma as the *second* item, not the first (which is for Klatskin's Tumor).

@susannasiebert, what do you think should be the solution here? Perhaps the client should query this information directly (using a drug ID). Or if the diseases query could be tweaked to always display exact matches first, then this issues could be solve w/o client modifications.

**Comment by jmcmichael** [comment]
This fix has been incorporated into the client, closing.
