### ISSUE TITLE
npm install fails with package ansi-styles-2.2.0 404 error

### ISSUE THREAD

**Issue by vipints** [griffithlab/civic-client#852]
Hello CIViC team, 

I trying to setup an instance of `civic-client` on a RHEL 7 server.  When I start the installation step: 

`npm install`

ends up with package ansi-styles-2.2.0 not found error.   

`3168 verbose stack Error: 404 Not Found: ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`

The next version of the package is available `https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz` but not sure where to change this required package version in the install script. Could you please help me with this. 

node -v 
v8.9.4
npm -v 
5.6.0 

Please let me know if you need any additional information from my side. 
Vipin

**Comment by jmcmichael** [comment]
Hi @vipints, try using yarn instead of npm for the installation. Installation instructions here:

https://yarnpkg.com/lang/en/docs/install/#linux-tab

Once installed, just execute 'yarn' from the root directory of civic-client.

Yarn is a replacement for npm, and it appears to do a better job of managing complex inter-dependencies. I've been using it for installing npm dependencies for awhile and haven't run into this issue. Let us know if this works for you.

**Comment by vipints** [comment]
Thanks @jmcmichael! I have followed with `yarn` and it worked! 

```shell
[mpe@civic: ~/civic-client]# yarn install 
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
warning path@0.4.9: The engine "ender" appears to be invalid.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
success Saved lockfile.
Done in 37.48s.
```
