### ISSUE TITLE
add 'Relevance' column to Gene and Variant browse grid

### ISSUE THREAD

**Issue by jmcmichael** [griffithlab/civic-client#876]
Server now provides a relevance score that can be used for sorting:

https://github.com/griffithlab/civic-server/issues/141

Gene and Variant browse grids need an additional column so users can sort by relevance.

**Comment by susannasiebert** [comment]
https://github.com/griffithlab/civic-client/pull/995 adds this column to the variant browse table and makes it the default sort column for that table. We'll need to talk about how we would incorporate this into the gene browse table, is desired, since that would require some sort of aggregation of the scores of all the gene's variants.

**Comment by susannasiebert** [comment]
This was discussed during the meeting and decided that we don't need to add the score to the gene browse table.
