### ISSUE TITLE
add evidence from source suggestions is associating an incorrect gene name

### ISSUE THREAD

**Issue by kkrysiak** [griffithlab/civic-client#887]
Clicking the + for this suggested source fills in the gene as GAMT when it should be TP53. https://civicdb.org/sources/2232/summary

**Comment by obigriffith** [comment]
Here's another example where starting and add evidence form from a source suggestion is pre-filling the wrong gene symbol (FTO instead of ALK in this guess)

https://civicdb.org/sources/2038/summary

**Comment by jmcmichael** [comment]
This is looks like a combination server/client issue.

The gene field needs to be populated w/ an object from the server that includes the gene ID, so the controller for that field takes the gene name and performs a search using the `/genes?name=[name]&detailed=false` URL and then takes the first result from the returned set of gene objects. In the past, this was reliably the same as the gene name, but since we've added aliases to this search, this method is not as reliable. If the gene has an alias that better matches the search string, it will be returned and the field populated with that gene's primary name. At least that's my folk understanding of what's going on under the hood.

This looks to be the case for the search that returns `FTO` for the name `ALK` - note how `FTO` is the first result, and has `ALKBH9`:

https://civicdb.org/api/genes?name=ALK&detailed=false

Perhaps we need an 'exactMatch' option or endpoint, like we have with diseases. @acoffman @susannasiebert
