### ISSUE TITLE
Clinical Trial doubled field

### ISSUE THREAD

**Issue by arpaddanos** [griffithlab/civic-client#912]
in EID 6178 and 6179 note that the clinical trial field is doubled, and the ID appears twice.

**Comment by susannasiebert** [comment]
These were imported twice because they get returned in duplicate from the pubmed API. E.g., https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&id=28891408&retmode=xml for EID `6178` returns:
```
..
<DataBank>
<DataBankName>ClinicalTrials.gov</DataBankName>
<AccessionNumberList>
<AccessionNumber>NCT01682083</AccessionNumber>
<AccessionNumber>NCT01682083</AccessionNumber>
</AccessionNumberList>
</DataBank>
..
````
We should make sure that we unique this list before we save it in our database.

I will also delete the duplicate entries.
