### ISSUE TITLE
Evidence types and clinical significances

### ISSUE THREAD

**Issue by stuppie** [griffithlab/civic-client#945]
I'm looking at all of the evidences returned from the API and comparing with the table here: https://civicdb.org/help/evidence/evidence-types
There's a couple that don't match.

Predictive: There are a couple with clinical_significance: 'Adverse Response' or 'Reduced Sensitivity'. Not sure what adverse response means, but I'm guessing reduced sensitivity should be Resistance?

Predisposing: There are a couple with clinical_significance: 'Positive'. 

Prognostic: There are a couple with clinical_significance: 'Positive' or 'Negative'. Should be "Good" or "Poor" ?

Also, there are some that are 'N/A' or None, or vice-versa. I'm guessing None should be "N/A" or do they mean different things?

Thanks!!

**Comment by obigriffith** [comment]
For Predictive: 'Adverse Response' or 'Reduced Sensitivity' are valid clinical_significance values. They were added recently for compliance with MVLD or simply haven't been used much yet. Adverse response refers to variants that don't predict sensitivity or resistance but instead predict and adverse drug response (negative side effect) which is a distinct concept. Reduced sensitivity is complicated to explain but basically it is used to reflect a relative concept. The variant does not confer resistance. Due to its identify it may be expected to confer sensitivity but it has reduced sensitivity compared to some reference/canonical variant. 

Predisposing: 'Positive' is no longer a valid value. These should be corrected.

Prognostic: Correct. Those are outdated and need to be corrected. 'Positive' or 'Negative'. Should be "Better" or "Poor" ?

There should only be "N/A" which is a valid but rarely used clinical significance for each evidence type. The "None" entries are historical artifacts that should be corrected. Do you mind sending the list of problem evidence items you identified?

**Comment by malachig** [comment]
I believe most/all these `Adverse Response` entries are correct.  Adverse Response is a supported type.  It means the variants predict an adverse response (e.g. some kind of toxicity, etc.).  These are basically pharmacogenetics entries.

**Comment by susannasiebert** [comment]
@obigriffith @malachig can this issue be resolved?
